### ISSUE TITLE
Missing required key 'Bucket' in params

### ISSUE THREAD

**Issue by michaelbachmann** [colinmeinke/ghost-storage-adapter-s3#14]
Whenever I attempt to add images I get
`Missing required key 'Bucket' in params`

Config is setup as...
```
storage: {
  active: 's3',
  s3: {
    accessKeyId: process.env.S3_ACCESS_KEY_ID,
    bucket: process.env.S3_BUCKET_NAME,
    region: process.env.S3_BUCKET_REGION,
    secretAccessKey: process.env.S3_ACCESS_SECRET_KEY
  }
}
```

Console out...
```
ghost_1  | ERROR: Missing required key 'Bucket' in params
ghost_1  |
ghost_1  |  MissingRequiredParameter: Missing required key 'Bucket' in params
ghost_1  |     at ParamValidator.fail (/app/content/storage/s3/node_modules/aws-sdk/lib/param_validator.js:50:37)
ghost_1  |     at ParamValidator.validateStructure (/app/content/storage/s3/node_modules/aws-sdk/lib/param_validator.js:61:14)
ghost_1  |     at ParamValidator.validateMember (/app/content/storage/s3/node_modules/aws-sdk/lib/param_validator.js:88:21)
ghost_1  |     at ParamValidator.validate (/app/content/storage/s3/node_modules/aws-sdk/lib/param_validator.js:34:10)
ghost_1  |     at Request.VALIDATE_PARAMETERS (/app/content/storage/s3/node_modules/aws-sdk/lib/event_listeners.js:114:42)
ghost_1  |     at Request.callListeners (/app/content/storage/s3/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
ghost_1  |     at callNextListener (/app/content/storage/s3/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
ghost_1  |     at /app/content/storage/s3/node_modules/aws-sdk/lib/event_listeners.js:74:9
ghost_1  |     at finish (/app/content/storage/s3/node_modules/aws-sdk/lib/config.js:313:7)
ghost_1  |     at /app/content/storage/s3/node_modules/aws-sdk/lib/config.js:331:9
ghost_1  |     at Credentials.get (/app/content/storage/s3/node_modules/aws-sdk/lib/credentials.js:126:7)
ghost_1  |     at getAsyncCredentials (/app/content/storage/s3/node_modules/aws-sdk/lib/config.js:325:24)
ghost_1  |     at Config.getCredentials (/app/content/storage/s3/node_modules/aws-sdk/lib/config.js:345:9)
ghost_1  |     at Request.VALIDATE_CREDENTIALS (/app/content/storage/s3/node_modules/aws-sdk/lib/event_listeners.js:69:26)
ghost_1  |     at Request.callListeners (/app/content/storage/s3/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
ghost_1  |     at Request.emit (/app/content/storage/s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
ghost_1  |     at Request.emit (/app/content/storage/s3/node_modules/aws-sdk/lib/request.js:673:14)
ghost_1  |     at Request.transition (/app/content/storage/s3/node_modules/aws-sdk/lib/request.js:22:10)
ghost_1  |     at AcceptorStateMachine.runTo (/app/content/storage/s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
ghost_1  |     at Request.runTo (/app/content/storage/s3/node_modules/aws-sdk/lib/request.js:399:15)
ghost_1  |     at /app/content/storage/s3/node_modules/aws-sdk/lib/request.js:781:12
ghost_1  |     at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:300:9)
```

Thanks for the help mate!

**Comment by michaelbachmann** [comment]
Nevermind figured it out! Sorry!

**Comment by parkerproject** [comment]
@michaelbachmann how did you figure this out cos I am having the same issue since upgrading to Ghost 5
