### ISSUE TITLE
implement read method (required for favicon)

### ISSUE THREAD

**Issue by matitalatina** [colinmeinke/ghost-storage-adapter-s3#20]
## Steps to reproduce

* Upload an image in admin->General->Publication icon and Save. I can see correctly the image in admin panel. So the upload works as expected.
* Go to website.
* favicon.png doesn't work.
* I you go to /favicon.png it says: Error 500 - Cannot read property 'then' of undefined.

[Ghost 1.0.0 has changed favicon logic](https://themes.ghost.org/v1.0.0/docs/migrate-to-ghost-1-0-0#section-favicon-code-is-no-longer-needed-) and I can't override it with my custom logic.

Essentially it uses read method that is not implemented.

## Stacktrace

```
TypeError: Cannot read property 'then' of undefined
    at serveFavicon (/usr/src/app/versions/1.5.1/core/server/middleware/serve-favicon.js:54:21)
    at Layer.handle [as handle_request] (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/src/app/versions/1.5.1/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:275:10)
    at query (/usr/src/app/versions/1.5.1/node_modules/express/lib/middleware/query.js:44:5)
    at Layer.handle [as handle_request] (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:174:3)
    at EventEmitter.handle (/usr/src/app/versions/1.5.1/node_modules/express/lib/application.js:174:10)
    at mounted_app (/usr/src/app/versions/1.5.1/node_modules/express/lib/application.js:230:10)
    at Layer.handle [as handle_request] (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/index.js:275:10)
    at ghostLocals (/usr/src/app/versions/1.5.1/core/server/middleware/ghost-locals.js:15:5)
    at Layer.handle [as handle_request] (/usr/src/app/versions/1.5.1/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by matitalatina** [comment]
I implemented this way that method:

```
read (options) {
    options = options || {};
    // remove trailing slashes
    options.path = (options.path || '').replace(/\/$|\\$/, '');
    return new Promise((resolve, reject) => {
      this.s3()
        .getObject({
          Bucket: this.bucket,
          Key: stripLeadingSlash(options.path)
        })
        .promise()
        .then((data) => resolve(data.Body.toString('utf8')))
        .catch(() => reject(false))
    })
  }
```

But now it redirects `http://site/favicon.png` to `http://site/favicon.png/` and it gives 404.

**Comment by colinmeinke** [comment]
Would definitely love a PR for a working `read` method. I haven't touched ghost in a while, so not sure why your attempt isn't working @matitalatina

**Comment by colinmeinke** [comment]
Closed by https://github.com/colinmeinke/ghost-storage-adapter-s3/releases/tag/v2.2.0
