### ISSUE TITLE
Cannot Get Past: NAME: IncorrectUsageError

### ISSUE THREAD

**Issue by etanb** [colinmeinke/ghost-storage-adapter-s3#30]
Hi,

I've been attempting to use the `ghost-storage-adapter-s3` with my Ghost / Docker implementation and cannot get past the following error: 

```
ghost_1  | NAME: IncorrectUsageError
ghost_1  | CODE: MODULE_NOT_FOUND
ghost_1  | MESSAGE: We have detected an error in your custom storage adapter.
ghost_1  | 
ghost_1  | level:critical
ghost_1  | 
ghost_1  | IncorrectUsageError: We have detected an error in your custom storage adapter.
ghost_1  |     at new IncorrectUsageError (/var/lib/ghost/versions/1.20.3/node_modules/ghost-ignition/lib/errors/index.js:79:23)
ghost_1  |     at Object.getStorage (/var/lib/ghost/versions/1.20.3/core/server/adapters/storage/index.js:42:19)
ghost_1  |     at setupSiteApp (/var/lib/ghost/versions/1.20.3/core/server/web/site/app.js:69:73)
ghost_1  |     at setupParentApp (/var/lib/ghost/versions/1.20.3/core/server/web/parent-app.js:54:36)
ghost_1  |     at /var/lib/ghost/versions/1.20.3/core/server/index.js:81:48
ghost_1  |     at Function.Module._resolveFilename (module.js:469:15)
ghost_1  |     at Function.Module._load (module.js:417:25)
ghost_1  |     at Module.require (module.js:497:17)
ghost_1  |     at require (internal/module.js:20:19)
ghost_1  |     at Object.<anonymous> (/content/adapters/storage/ghost-imgur/index.js:4:19)
ghost_1  |     at Module._compile (module.js:570:32)
ghost_1  |     at Object.Module._extensions..js (module.js:579:10)
ghost_1  |     at Module.load (module.js:487:32)
ghost_1  |     at tryModuleLoad (module.js:446:12)
ghost_1  |     at Function.Module._load (module.js:438:3)
ghost_1  |     at Module.require (module.js:497:17)
ghost_1  |     at require (internal/module.js:20:19)
ghost_1  |     at Object.getStorage (/var/lib/ghost/versions/1.20.3/core/server/adapters/storage/index.js:32:25)
ghost_1  |     at setupSiteApp (/var/lib/ghost/versions/1.20.3/core/server/web/site/app.js:69:73)
ghost_1  |     at setupParentApp (/var/lib/ghost/versions/1.20.3/core/server/web/parent-app.js:54:36)
ghost_1  |     at /var/lib/ghost/versions/1.20.3/core/server/index.js:81:48
ghost_1  | From previous event:
ghost_1  |     at init (/var/lib/ghost/versions/1.20.3/core/server/index.js:77:8)
ghost_1  |     at makeGhost (/var/lib/ghost/versions/1.20.3/core/index.js:11:12)
ghost_1  |     at Object.<anonymous> (/var/lib/ghost/versions/1.20.3/index.js:20:1)
ghost_1  |     at Module._compile (module.js:570:32)
ghost_1  |     at Object.Module._extensions..js (module.js:579:10)
ghost_1  |     at Module.load (module.js:487:32)
ghost_1  |     at tryModuleLoad (module.js:446:12)
ghost_1  |     at Function.Module._load (module.js:438:3)
ghost_1  |     at Module.runMain (module.js:604:10)
ghost_1  |     at run (bootstrap_node.js:383:7)
ghost_1  |     at startup (bootstrap_node.js:149:9)
ghost_1  |     at bootstrap_node.js:496:3

```

My dockerfile looks as follows:

```
FROM ghost:1.20.3

# Install build dependencies
RUN apt-get update \
 && apt-get install -y --force-yes --no-install-recommends\
      apt-transport-https \
      ssh-client \
      build-essential \
      curl \
      git \
      python-all \
      rlwrap \
      unzip \
      jq \
  && apt-get upgrade -y --force-yes \
  && rm -rf /var/lib/apt/lists/*;

RUN curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" \
 && unzip awscli-bundle.zip \
 && ./awscli-bundle/install -b ~/bin/aws \
 && ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
ENV AWS_DEFAULT_REGION us-east-1

# We want to use a non-standard `content/` path for Ghost as the base image 
# mounts the default location as a VOLUME meaning we cannot place our theme or
# s3 adapter into it as part of the dockerfile:
# https://github.com/docker-library/ghost/blob/master/1/debian/Dockerfile#L76
ENV paths__contentPath "/opt/ghost/content"
RUN mkdir -p $paths__contentPath/themes $paths__contentPath/adapters/storage

# Now build our actual source files
COPY PlaidBlog $paths__contentPath/themes/PlaidBlog/
RUN cd $paths__contentPath/themes/PlaidBlog/ && make setup
RUN cd $paths__contentPath/themes/PlaidBlog/ && make clean
RUN cd $paths__contentPath/themes/PlaidBlog/ && make build

# To use s3 as a storage system for static content (such as post images) we
# need to copy the adapter to the proper location in the ghost content path.
RUN mv $paths__contentPath/themes/PlaidBlog/node_modules/ghost-storage-adapter-s3 $paths__contentPath/adapters/storage/s3

COPY start.sh secrets.sh secrets.json ./

# Old ENTRYPOINT behavior mimicked in start.sh
# https://github.com/docker-library/ghost/blob/962323a525d020a49a9165ba62f85098b8e5e09f/1/debian/Dockerfile#L79
ENTRYPOINT []
CMD ["./start.sh"]
```

**Comment by colinmeinke** [comment]
Maybe @johnbarney can help you? Not sure if this is relevant https://github.com/colinmeinke/ghost-storage-adapter-s3/issues/24

**Comment by etanb** [comment]
Looks similar! My current workaround is to just place it directly into: `RUN mv $paths__contentPath/themes/PlaidBlog/node_modules/ghost-storage-adapter-s3 /var/lib/ghost/versions/1.20.3/core/server/adapters/storage/s3`

**Comment by etanb** [comment]
@colinmeinke I'm getting this error now:

`TypeError: _awsSdk2.default.config.setPromisesDependency is not a function`

Any idea how to get by this?

**Comment by etanb** [comment]
This seems like a relevant thread: https://github.com/aws/aws-sdk-js/issues/1076

**Comment by johnbarney** [comment]
Hi @etanb,

What I've done is to create two Dockerfiles. One for local testing, and one for deployment.

Dockerfile
```
FROM ghost:alpine

RUN cd current &&                                 \
    npm install ghost-storage-adapter-s3 &&       \
    mkdir -p ./content/adapters/storage &&        \
    cp -r ./node_modules/ghost-storage-adapter-s3 \
          ./core/server/adapters/storage/s3 &&    \
    rm -f /var/lib/ghost/content/data/ghost.db && \
    rm -f /var/lib/ghost/configuration.production.json

ENV server__host 0.0.0.0
ENV paths__contentPath /var/lib/ghost/content
```

Dockerfile.prod
```
FROM blog

COPY mytheme/ content.orig/themes/mytheme
```

My build function is as follows:

build.sh
```bash
build () {
  echo "Verifying theme"
  gscan ./theme
  echo "Preparing theme"
  cd theme
  npm install
  gulp zip
  cd ..
  cp theme/dist/mytheme.zip .
  unzip mytheme.zip -d mytheme
  docker build -t blog .
  docker build --file Dockerfile.prod -t $IMAGE .
  docker push $IMAGE
}
```

I may have over-engineered my solution but I stopped at *working*. I hope this helps!

John B.

**Comment by colinmeinke** [comment]
@johnbarney thanks for the reply! @etanb did that help?

**Comment by etanb** [comment]
I just use a `docker-compose.yml` file for local.

I'm not sure that was even the issue I was experiencing. The weird way my issue was fixed was by actually adding the compiled module to my repo which includes running `npm install` && `npm run build`.
