### ISSUE TITLE
It seems not working on Ghost 2.x

### ISSUE THREAD

**Issue by yuhr123** [colinmeinke/ghost-storage-adapter-s3#39]
I have tried to config this adapter on Ghost 2.x, but can not start Ghost service if I add "storage" related info into the `config.production.json` file.

**Comment by yuhr123** [comment]
Try on Ghost 1.x it is not working too.

```json
{
...
"storage": {
    "active": "s3",
    "s3": {
      "accessKeyId": "myKeyID",
      "secretAccessKey": "myAccessKey",
      "bucket": "myBucketName"
    }
  }
}
```

When I execute `ghost restart`:
```shell
$ ghost restart
Found a development config but not a production config, running in development mode instead
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✖ Starting Ghost
A GhostError occurred.

Message: We have detected an error in your custom storage adapter.

Debug Information:
    OS: LinuxMint, v19
    Node Version: v8.11.4
    Ghost-CLI Version: 1.9.1
    Environment: development
    Command: 'ghost start'

Additional log info available in:~/.ghost/logs/ghost-cli-debug-2018-08-24T08_20_57_339Z.log

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```

The log content:

```shell
$ cat ~/.ghost/logs/ghost-cli-debug-2018-08-24T08_20_57_339Z.log
Debug Information:
    OS: LinuxMint, v19
    Node Version: v8.11.4
    Ghost-CLI Version: 1.9.1
    Environment: development
    Command: 'ghost start'
Message: We have detected an error in your custom storage adapter.
Stack: Error: We have detected an error in your custom storage adapter.
    at ChildProcess.cp.on (~/.local/lib/node_modules/ghost-cli/lib/utils/local-process.js:63:35)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by NotMyself** [comment]
Hey, @yuhr123 you closed this issue but didn't say how you fixed it. Can you point me in the right direction?

**Comment by frippz** [comment]
Hey, @NotMyself. I stumbled across [this blog post](https://it.ismy.fun/2018/08/26/ghost-custom-storage-module/) and gave it a go. I actually seems to be working just fine. The blog post seem to be in Chinese, but Google Translate will help you out there. 😉

Good luck, mate!

**Comment by NotMyself** [comment]
Thanks, guys. I was able to get it to work for me as well.
