### ISSUE TITLE
ERROR: We cannot find your adapter in

### ISSUE THREAD

**Issue by pascalandy** [colinmeinke/ghost-storage-adapter-s3#5]
Hey Colin,

Getting this error when starting ghost :

```
npm info it worked if it ends with ok
npm info using npm@2.15.9
npm info using node@v4.6.1
npm info prestart ghost@0.11.2
npm info start ghost@0.11.2

> ghost@0.11.2 start /usr/src/ghost
> node index


ERROR: We cannot find your adpter in: /var/lib/ghost/storage/ or: /usr/src/ghost/core/server/storage/

 Error
    at Error.IncorrectUsage (/usr/src/ghost/core/server/errors/incorrect-usage.js:3:18)
    at Object.getStorage (/usr/src/ghost/core/server/storage/index.js:45:19)
    at setupMiddleware (/usr/src/ghost/core/server/middleware/index.js:126:44)
    at /usr/src/ghost/core/server/index.js:188:9
    at tryCatcher (/usr/src/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/usr/src/ghost/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/usr/src/ghost/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/src/ghost/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/src/ghost/node_modules/bluebird/js/release/async.js:138:16)

npm info poststart ghost@0.11.2
npm info ok
```

### Observation 1

About:
```ERROR: We cannot find your adpter in: /var/lib/ghost/storage/ or: /usr/src/ghost/core/server/storage/
```

It's weird that the error's path is `/var/lib/ghost/storage` and NOT `/var/lib/ghost/content/storage`

### Observation 2
I see errors related to `bluebird`. Could it be possible we need to fix [this](https://github.com/kelyvin/ghost-s3-service/commit/79b7f2c981cfb183790ee57d1fb133351b6acb9a)?

This is how my directories look like:

```
root@c6adb074c8d1:/usr/src/ghost# ls -lh
total 292K
-rw-r--r--  1 root root    0 Dec 19 18:22 DIRgst2-base-0.11.2-colinmeinke_BYPascal-Andy_2016-12-19_18h22_51-5H.txt
-rw-r--r--  1 root root  32K Oct 11 12:40 Gruntfile.js
-rw-r--r--  1 root root 1.1K Oct 11 12:40 LICENSE
-rw-r--r--  1 root root 2.9K Oct 11 12:40 PRIVACY.md
-rw-r--r--  1 root root 4.6K Oct 11 12:40 README.md
-rw-r--r--  1 root root 4.5K Oct 11 12:40 config.example.js
drwxr-xr-x  7 root root 4.0K Dec 19 18:23 content
drwxr-xr-x  5 root root 4.0K Oct 11 12:51 core
-rw-r--r--  1 root root  725 Oct 11 12:40 index.js
drwxr-xr-x 93 root root 4.0K Dec 19 18:22 node_modules
-rw-r--r--  1 root root 164K Oct 11 12:51 npm-shrinkwrap.json
-rw-r--r--  1 root root 3.0K Oct 11 12:40 package.json
-rw-r--r--  1 root root  52K Dec 19 18:24 tree.txt

root@c6adb074c8d1:/usr/src/ghost/content/storage# ls
s3

root@c6adb074c8d1:/usr/src/ghost/content/storage/s3# ls -lh
total 36K
-rw-r--r-- 1 root root 3.2K Dec 19 18:23 CODE_OF_CONDUCT.md
-rw-r--r-- 1 root root 2.4K Dec 19 18:23 CONTRIBUTING.md
-rw-r--r-- 1 root root  808 Dec 19 18:23 LICENSE.md
-rw-r--r-- 1 root root  579 Dec 19 18:23 README.md
-rw-r--r-- 1 root root 6.2K Dec 19 18:23 index.js
drwxr-xr-x 3 root root 4.0K Dec 19 18:23 node_modules
-rw-r--r-- 1 root root 2.5K Dec 19 18:23 package.json
drwxr-xr-x 2 root root 4.0K Dec 19 18:23 src
```

### Observation 3
The **index.js** file is not the same as what I see from https://github.com/colinmeinke/ghost-storage-adapter-s3/blob/master/src/index.js

```
root@c6adb074c8d1:/usr/src/ghost/content/storage/s3# cat index.js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _slicedToArray = function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; }();

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _awsSdk = require('aws-sdk');

var _awsSdk2 = _interopRequireDefault(_awsSdk);

var _base = require('../../../core/server/storage/base');

var _base2 = _interopRequireDefault(_base);

var _path = require('path');

var _bluebird = require('bluebird');

var _bluebird2 = _interopRequireDefault(_bluebird);

var _fs = require('fs');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var readFileAsync = (0, _bluebird.promisify)(_fs.readFile);

var stripLeadingSlash = function stripLeadingSlash(s) {
  return s.indexOf('/') === 0 ? s.substring(1) : s;
};

var Store = function (_BaseStore) {
  _inherits(Store, _BaseStore);

  function Store() {
    var config = arguments.length <= 0 || arguments[0] === undefined ? {} : arguments[0];

    _classCallCheck(this, Store);

    var _this = _possibleConstructorReturn(this, (Store.__proto__ || Object.getPrototypeOf(Store)).call(this, config));

    _awsSdk2.default.config.setPromisesDependency(_bluebird2.default);

    var accessKeyId = config.accessKeyId;
    var assetHost = config.assetHost;
    var bucket = config.bucket;
    var region = config.region;
    var secretAccessKey = config.secretAccessKey;
    var pathPrefix = config.pathPrefix;


    _this.accessKeyId = accessKeyId;
    _this.bucket = bucket;
    _this.host = assetHost ? assetHost : 'https://s3' + (region === 'us-east-1' ? '' : '-' + region) + '.amazonaws.com/' + bucket;
    _this.region = region;
    _this.secretAccessKey = secretAccessKey;
    _this.pathPrefix = stripLeadingSlash(pathPrefix || '');
    return _this;
  }

  _createClass(Store, [{
    key: 'delete',
    value: function _delete(fileName, targetDir) {
      var _this2 = this;

      var directory = targetDir || this.getTargetDir(this.pathPrefix);

      return new _bluebird2.default(function (resolve, reject) {
        return _this2.s3().deleteObject({
          Bucket: _this2.bucket,
          Key: stripLeadingSlash((0, _path.join)(directory, fileName))
        }).promise().then(function () {
          return resolve(true);
        }).catch(function () {
          return resolve(false);
        });
      });
    }
  }, {
    key: 'exists',
    value: function exists(fileName) {
      var _this3 = this;

      return new _bluebird2.default(function (resolve, reject) {
        return _this3.s3().getObject({
          Bucket: _this3.bucket,
          Key: stripLeadingSlash(fileName)
        }).promise().then(function () {
          return resolve(true);
        }).catch(function () {
          return resolve(false);
        });
      });
    }
  }, {
    key: 's3',
    value: function s3() {
      return new _awsSdk2.default.S3({
        accessKeyId: this.accessKeyId,
        bucket: this.bucket,
        region: this.region,
        secretAccessKey: this.secretAccessKey
      });
    }
  }, {
    key: 'save',
    value: function save(image, targetDir) {
      var _this4 = this;

      var directory = targetDir || this.getTargetDir(this.pathPrefix);

      return new _bluebird2.default(function (resolve, reject) {
        _bluebird2.default.all([_this4.getUniqueFileName(_this4, image, directory), readFileAsync(image.path)]).then(function (_ref) {
          var _ref2 = _slicedToArray(_ref, 2);

          var fileName = _ref2[0];
          var file = _ref2[1];
          return _this4.s3().putObject({
            ACL: 'public-read',
            Body: file,
            Bucket: _this4.bucket,
            CacheControl: 'max-age=' + 30 * 24 * 60 * 60,
            ContentType: image.type,
            Key: stripLeadingSlash(fileName)
          }).promise().then(function () {
            return resolve(_this4.host + '/' + fileName);
          });
        }).catch(function (error) {
          return reject(error);
        });
      });
    }
  }, {
    key: 'serve',
    value: function serve() {
      return function (req, res, next) {
        next();
      };
    }
  }]);

  return Store;
}(_base2.default);

exports.default = Store;
module.exports = exports['default'];
```

### Observation 4

In other Ghost adaptors projects [like this one](https://github.com/kelyvin/ghost-s3-service) they require to:

```
Create a file called `index.js` (./content/storage/index.js) and insert the following code

'use strict';
module.exports = require('ghost-storage-adapter-s3'); 
```

I guess it's not need here but I'm just trying to find leads about why Ghost is complaining.

Thanks in advance!
twitter.com/_pascalandy

**Comment by colinmeinke** [comment]
Why do you think this error relates to this library?

**Comment by colinmeinke** [comment]
I think your content path must be incorrectly configured. It thinks your content path is root, not '/content'. This isn't an error with this lib.
