### ISSUE TITLE
IMAGE_SIZE_URL statusCode 403

### ISSUE THREAD

**Issue by konstantinvlasenko** [colinmeinke/ghost-storage-adapter-s3#75]
Hi everyone,
Seems like I am doing something wrong. But can't figure it out. Getting error below when I try to start Ghost (if adapter enabled).
Any help appreciated!

**Environment:** 

- AWS ECS (Amazon Linux 2)
- Instance IAM Role has S3 Full Access
- Bucket exists (but empty)

**Config:**
`"storage": {
    "active": "s3",
    "s3": {
      "bucket: "my-bucket",
      "pathPrefix": "test"
    }`

**Error:**
`{
	"name": "Log",
	"hostname": "ip-10-192-50-105.ec2.internal",
	"pid": 15984,
	"level": 50,
	"err": {
		"id": "f5418a30-e640-11ea-bb9f-155e217295a3",
		"domain": "https://MY_DOMAIN.org",
		"code": "IMAGE_SIZE_URL",
		"name": "InternalServerError",
		"statusCode": 403,
		"level": "critical",
		"message": "Unknown Request error.",
		"context": "\"https://static.ghost.org/v3.0.0/images/publication-cover.png\"",
		"stack": "InternalServerError: Unknown Request error.\n    at new InternalServerError (/var/www/ghost/versions/3.31.1/node_modules/ghost-ignition/lib/errors/index.js:90:23)\n    at /var/www/ghost/versions/3.31.1/core/server/lib/image/image-size.js:176:31\n    at tryCatcher (/var/www/ghost/versions/3.31.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/3.31.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/ghost/versions/3.31.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/ghost/versions/3.31.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/ghost/versions/3.31.1/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/ghost/versions/3.31.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/ghost/versions/3.31.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/ghost/versions/3.31.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/ghost/versions/3.31.1/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:456:21)\n\nProbeError: bad status code: 403\n    at Request.<anonymous> (/var/www/ghost/versions/3.31.1/node_modules/probe-image-size/http.js:46:19)\n    at Request.emit (events.js:315:20)\n    at Request.EventEmitter.emit (domain.js:483:12)\n    at Request.onRequestResponse (/var/www/ghost/versions/3.31.1/node_modules/request/request.js:1059:10)\n    at ClientRequest.emit (events.js:315:20)\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)\n    at TLSSocket.socketOnData (_http_client.js:469:22)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at TLSSocket.Readable.push (_stream_readable.js:212:10)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)"
	},
	"msg": "Unknown Request error.",
	"time": "2020-08-24T19:35:25.524Z",
	"v": 0
}`

**Comment by shrmaky** [comment]
Hi @konstantinvlasenko which version of ghost are you using & what is your S3 implementation looks like?
